import Ember from 'ember';

export default Ember.Controller.extend({
  newsubject:{},
  newtyp:{},
  newmodul:{},
  actions:{
    addModul:function(){
      this.set('newmodul',this.store.createRecord('modul'));
      this.set("showCreateModulDialog",true);
    },
    editModul:function(m){
      this.set('newmodul',m);
      this.set("showEditModulDialog",true);
    },
    deleteObject:function(subject){
      this.set('newobject',subject);
      this.set('showDeleteDialog',true);
    },
    closeDeleteDialog:function(option){
      this.set('showDeleteDialog',false);
      if(option=="ok"){
        this.get('newobjekt').destroyRecord();
      }
      this.set('newobject',null);
    },
    closeModulDialog:function(option){
      if(option=="ok"){
        this.get('newmodul').save().then(null,this.ajaxError.bind(this))
      } else
      {
        if(this.get('showCreateModulDialog')){
          this.get('newmodul').unloadRecord();
      }
      }
      this.set('showCreateModulDialog',false);
      this.set('showEditModulDialog',false);
    },
    addSubject:function(){
      this.set('newsubject',this.store.createRecord('subject'));
      this.set("showCreateSubjectDialog",true);
    },
    editSubject:function(subject){
      this.set('newsubject',subject);
      this.set("showEditSubjectDialog",true);
    },
    closeSubjectDialog:function(option){
      if(option=="ok"){
        this.get('newsubject').save().then(null,this.ajaxError.bind(this))
      } else
      {
        if(this.get('showCreateSubjectDialog')){
          this.get('newsubject').unloadRecord();
      }
      }
      this.set('showCreateSubjectDialog',false);
      this.set('showEditSubjectDialog',false);
    },
    addTyp:function(){
      this.set('newtyp',this.store.createRecord('typ'));
      this.set("showCreateTypDialog",true);
    },
    editTyp:function(typ){
      this.set('newtyp',typ);
      this.set("showEditTypDialog",true);
    },
    closeTypDialog:function(option){
      if(option=="ok"){
        this.get('newtyp').save().then(null,this.ajaxError.bind(this))
      } else
      {
        if(this.get('showCreateTypDialog'))
        this.get('newtyp').unloadRecord();
      }
      this.set('showCreateTypDialog',false);
      this.set('showEditTypDialog',false);
    }
  }
});
