defaults: &default
  imap_server: <%= ENV['PRODUCTION_IMAP_SERVER'] %>
  imap_port: <%= ENV['PRODUCTION_IMAP_PORT'] %>
  use_ssl: true
  ignore_ssl_error: false
  email: <%= ENV['PRODUCTION_EMAIL_ADDRESS'] %>
  email_username: <%= ENV['PRODUCTION_EMAIL_USERNAME'] %>
  password: <%= ENV['PRODUCTION_EMAIL_PASSWORD'] %>
  box: <%= ENV['PRODUCTION_EMAIL_BOX'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
